### ISSUE TITLE
Crash when launching the game on another computer

### ISSUE THREAD

**Issue by nylnook** [flossmanualsfr/escoria#1]
Hola @punto- 

Today is cloned the repo on my main computer (stationary computer)... and the game crash at launch with "Attempt to call function 'call_defered' in base 'null instance' on a null instance' and pointing the line 4 of /globals/scene_base.gd

It's strange because it still work after a pull on my tablet. The two computer share the same Arch linux 64 bit distro (Antergos) with the same Godot version (v2.0.4.1)... the only difference I can see between the two is that the screen is larger that Full HD (2560x1440), and that it use an ATI card with ATI Open source drivers.

If I try to launch a single scene, the game also crash complaining it doesn't find the fonts, but the path seem correct...

Any idea ? Do you need some logs or screenshots, and which one ?

Have a nice trip in London !

**Comment by punto-** [comment]
```
                                                                                  Hi! It looks like it's probably not a hardware issue, just a missing file.. can you copy the console output (if you can get it from the actual text console instead of the editor panel even better) ‎from the page before the error?I'll do a clone here as soon as I'm at the computer.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the Orange network.                                                                                                                                                                                                                From: Camille BissuelSent: Monday, August 29, 2016 5:13 PMTo: flossmanualsfr/escoriaReply To: flossmanualsfr/escoriaCc: punto-; MentionSubject: [flossmanualsfr/escoria] Crash when launching the game on another computer (#1)Hola @punto- 
```

Today is cloned the repo on my main computer (stationary computer)... and the game crash at launch with "Attempt to call function 'call_defered' in base 'null instance' on a null instance' and pointing the line 4 of /globals/scene_base.gd

It's strange because it still work after a pull on my tablet. The two computer share the same Arch linux 64 bit distro (Antergos) with the same Godot version (v2.0.4.1)... the only difference I can see between the two is that the screen is larger that Full HD (2560x1440), and that it use an ATI card with ATI Open source drivers.

If I try to launch a single scene, the game also crash complaining it doesn't find the fonts, but the path seem correct...

Any idea ? Do you need some logs or screenshots, and which one ?

Have a nice trip in London !

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/flossmanualsfr/escoria","title":"flossmanualsfr/escoria","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/flossmanualsfr/escoria"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Crash when launching the game on another computer (#1)"}],"action":{"name":"View Issue","url":"https://github.com/flossmanualsfr/escoria/issues/1"}}}

**Comment by nylnook** [comment]
Hey, that was quick. here is the output from my console: 

```
[nylnook@nylnook-home device]$ godot main.scn 
ERROR: instance: Condition ' !ti ' is true. returned: __null
   At: core/object_type_db.cpp:283.
ERROR: poll: res://ui/fonts/Big_Bottom_Cartoon_AD_16.fnt:Resource of unrecognized type in file: BitmapFont
   At: core/io/resource_format_binary.cpp:743.
ERROR: load: Condition ' err!=OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:142.
ERROR: load: Failed loading resource: res://ui/fonts/Big_Bottom_Cartoon_AD_16.fnt
   At: core/io/resource_loader.cpp:218.
ERROR: poll: Can't load dependency: res://ui/fonts/Big_Bottom_Cartoon_AD_16.fnt
   At: core/io/resource_format_binary.cpp:681.
ERROR: load: Condition ' err!=OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:142.
ERROR: load: Failed loading resource: res://ui/dd_default.scn
   At: core/io/resource_loader.cpp:218.
ERROR: poll: Can't load dependency: res://ui/dd_default.scn
   At: core/io/resource_format_binary.cpp:681.
ERROR: load: Condition ' err!=OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:142.
ERROR: load: Failed loading resource: res://globals/dd_player.scn
   At: core/io/resource_loader.cpp:218.
ERROR: poll: Can't load dependency: res://globals/dd_player.scn
   At: core/io/resource_format_binary.cpp:681.
ERROR: load: Condition ' err!=OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:142.
ERROR: load: Failed loading resource: res://main.scn
   At: core/io/resource_loader.cpp:218.
ERROR: start: Can't autoload: res://main.scn
   At: main/main.cpp:1381.
ERROR: instance: Condition ' !ti ' is true. returned: __null
   At: core/object_type_db.cpp:283.
ERROR: poll: res://ui/fonts/Big_Bottom_Cartoon_AD_16.fnt:Resource of unrecognized type in file: BitmapFont
   At: core/io/resource_format_binary.cpp:743.
ERROR: load: Condition ' err!=OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:142.
ERROR: load: Failed loading resource: res://ui/fonts/Big_Bottom_Cartoon_AD_16.fnt
   At: core/io/resource_loader.cpp:218.
ERROR: poll: Can't load dependency: res://ui/fonts/Big_Bottom_Cartoon_AD_16.fnt
   At: core/io/resource_format_binary.cpp:681.
ERROR: load: Condition ' err!=OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:142.
ERROR: load: Failed loading resource: res://ui/dd_default.scn
   At: core/io/resource_loader.cpp:218.
ERROR: poll: Can't load dependency: res://ui/dd_default.scn
   At: core/io/resource_format_binary.cpp:681.
ERROR: load: Condition ' err!=OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:142.
ERROR: load: Failed loading resource: res://globals/dd_player.scn
   At: core/io/resource_loader.cpp:218.
ERROR: poll: Can't load dependency: res://globals/dd_player.scn
   At: core/io/resource_format_binary.cpp:681.
ERROR: load: Condition ' err!=OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:142.
ERROR: load: Failed loading resource: res://main.scn
   At: core/io/resource_loader.cpp:218.
ERROR: start: Failed loading scene: res://main.scn
   At: main/main.cpp:1433.
ERROR: free: Attempt to free invalid ID
   At: servers/spatial_sound/spatial_sound_server_sw.cpp:598.
ERROR: free: Attempt to free invalid ID
   At: servers/spatial_sound_2d/spatial_sound_2d_server_sw.cpp:612.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1904.
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:357.
```

**Comment by punto-** [comment]
```
                                                                                  It looks like it's having trouble opening that font.. are you sure you're using the same engine version on both computers?                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the Orange network.                                                                                                                                                                                                                From: Camille BissuelSent: Monday, August 29, 2016 5:33 PMTo: flossmanualsfr/escoriaReply To: flossmanualsfr/escoriaCc: punto-; MentionSubject: Re: [flossmanualsfr/escoria] Crash when launching the game on another computer (#1)Hey, that was quick. here is the output from my console: 
```

[nylnook@nylnook-home device]$ godot main.scn 
ERROR: instance: Condition ' !ti ' is true. returned: __null
   At: core/object_type_db.cpp:283.
ERROR: poll: res://ui/fonts/Big_Bottom_Cartoon_AD_16.fnt:Resource of unrecognized type in file: BitmapFont
   At: core/io/resource_format_binary.cpp:743.
ERROR: load: Condition ' err!=OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:142.
ERROR: load: Failed loading resource: res://ui/fonts/Big_Bottom_Cartoon_AD_16.fnt
   At: core/io/resource_loader.cpp:218.
ERROR: poll: Can't load dependency: res://ui/fonts/Big_Bottom_Cartoon_AD_16.fnt
   At: core/io/resource_format_binary.cpp:681.
ERROR: load: Condition ' err!=OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:142.
ERROR: load: Failed loading resource: res://ui/dd_default.scn
   At: core/io/resource_loader.cpp:218.
ERROR: poll: Can't load dependency: res://ui/dd_default.scn
   At: core/io/resource_format_binary.cpp:681.
ERROR: load: Condition ' err!=OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:142.
ERROR: load: Failed loading resource: res://globals/dd_player.scn
   At: core/io/resource_loader.cpp:218.
ERROR: poll: Can't load dependency: res://globals/dd_player.scn
   At: core/io/resource_format_binary.cpp:681.
ERROR: load: Condition ' err!=OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:142.
ERROR: load: Failed loading resource: res://main.scn
   At: core/io/resource_loader.cpp:218.
ERROR: start: Can't autoload: res://main.scn
   At: main/main.cpp:1381.
ERROR: instance: Condition ' !ti ' is true. returned: __null
   At: core/object_type_db.cpp:283.
ERROR: poll: res://ui/fonts/Big_Bottom_Cartoon_AD_16.fnt:Resource of unrecognized type in file: BitmapFont
   At: core/io/resource_format_binary.cpp:743.
ERROR: load: Condition ' err!=OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:142.
ERROR: load: Failed loading resource: res://ui/fonts/Big_Bottom_Cartoon_AD_16.fnt
   At: core/io/resource_loader.cpp:218.
ERROR: poll: Can't load dependency: res://ui/fonts/Big_Bottom_Cartoon_AD_16.fnt
   At: core/io/resource_format_binary.cpp:681.
ERROR: load: Condition ' err!=OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:142.
ERROR: load: Failed loading resource: res://ui/dd_default.scn
   At: core/io/resource_loader.cpp:218.
ERROR: poll: Can't load dependency: res://ui/dd_default.scn
   At: core/io/resource_format_binary.cpp:681.
ERROR: load: Condition ' err!=OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:142.
ERROR: load: Failed loading resource: res://globals/dd_player.scn
   At: core/io/resource_loader.cpp:218.
ERROR: poll: Can't load dependency: res://globals/dd_player.scn
   At: core/io/resource_format_binary.cpp:681.
ERROR: load: Condition ' err!=OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:142.
ERROR: load: Failed loading resource: res://main.scn
   At: core/io/resource_loader.cpp:218.
ERROR: start: Failed loading scene: res://main.scn
   At: main/main.cpp:1433.
ERROR: free: Attempt to free invalid ID
   At: servers/spatial_sound/spatial_sound_server_sw.cpp:598.
ERROR: free: Attempt to free invalid ID
   At: servers/spatial_sound_2d/spatial_sound_2d_server_sw.cpp:612.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1904.
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:357.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/flossmanualsfr/escoria","title":"flossmanualsfr/escoria","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/flossmanualsfr/escoria"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nylnook in #1: Hey, that was quick. here is the output from my console: \r\n\r\n`\r\n[nylnook@nylnook-home device]$ godot main.scn \r\nERROR: instance: Condition ' !ti ' is true. returned: __null\r\n   At: core/object_type_db.cpp:283.\r\nERROR: poll: res://ui/fonts/Big_Bottom_Cartoon_AD_16.fnt:Resource of unrecognized type in file: BitmapFont\r\n   At: core/io/resource_format_binary.cpp:743.\r\nERROR: load: Condition ' err!=OK ' is true. returned: RES()\r\n   At: core/io/resource_loader.cpp:142.\r\nERROR: load: Failed loading resource: res://ui/fonts/Big_Bottom_Cartoon_AD_16.fnt\r\n   At: core/io/resource_loader.cpp:218.\r\nERROR: poll: Can't load dependency: res://ui/fonts/Big_Bottom_Cartoon_AD_16.fnt\r\n   At: core/io/resource_format_binary.cpp:681.\r\nERROR: load: Condition ' err!=OK ' is true. returned: RES()\r\n   At: core/io/resource_loader.cpp:142.\r\nERROR: load: Failed loading resource: res://ui/dd_default.scn\r\n   At: core/io/resource_loader.cpp:218.\r\nERROR: poll: Can't load dependency: res://ui/dd_default.scn\r\n   At: core/io/resource_format_binary.cpp:681.\r\nERROR: load: Condition ' err!=OK ' is true. returned: RES()\r\n   At: core/io/resource_loader.cpp:142.\r\nERROR: load: Failed loading resource: res://globals/dd_player.scn\r\n   At: core/io/resource_loader.cpp:218.\r\nERROR: poll: Can't load dependency: res://globals/dd_player.scn\r\n   At: core/io/resource_format_binary.cpp:681.\r\nERROR: load: Condition ' err!=OK ' is true. returned: RES()\r\n   At: core/io/resource_loader.cpp:142.\r\nERROR: load: Failed loading resource: res://main.scn\r\n   At: core/io/resource_loader.cpp:218.\r\nERROR: start: Can't autoload: res://main.scn\r\n   At: main/main.cpp:1381.\r\nERROR: instance: Condition ' !ti ' is true. returned: __null\r\n   At: core/object_type_db.cpp:283.\r\nERROR: poll: res://ui/fonts/Big_Bottom_Cartoon_AD_16.fnt:Resource of unrecognized type in file: BitmapFont\r\n   At: core/io/resource_format_binary.cpp:743.\r\nERROR: load: Condition ' err!=OK ' is true. returned: RES()\r\n   At: core/io/resource_loader.cpp:142.\r\nERROR: load: Failed loading resource: res://ui/fonts/Big_Bottom_Cartoon_AD_16.fnt\r\n   At: core/io/resource_loader.cpp:218.\r\nERROR: poll: Can't load dependency: res://ui/fonts/Big_Bottom_Cartoon_AD_16.fnt\r\n   At: core/io/resource_format_binary.cpp:681.\r\nERROR: load: Condition ' err!=OK ' is true. returned: RES()\r\n   At: core/io/resource_loader.cpp:142.\r\nERROR: load: Failed loading resource: res://ui/dd_default.scn\r\n   At: core/io/resource_loader.cpp:218.\r\nERROR: poll: Can't load dependency: res://ui/dd_default.scn\r\n   At: core/io/resource_format_binary.cpp:681.\r\nERROR: load: Condition ' err!=OK ' is true. returned: RES()\r\n   At: core/io/resource_loader.cpp:142.\r\nERROR: load: Failed loading resource: res://globals/dd_player.scn\r\n   At: core/io/resource_loader.cpp:218.\r\nERROR: poll: Can't load dependency: res://globals/dd_player.scn\r\n   At: core/io/resource_format_binary.cpp:681.\r\nERROR: load: Condition ' err!=OK ' is true. returned: RES()\r\n   At: core/io/resource_loader.cpp:142.\r\nERROR: load: Failed loading resource: res://main.scn\r\n   At: core/io/resource_loader.cpp:218.\r\nERROR: start: Failed loading scene: res://main.scn\r\n   At: main/main.cpp:1433.\r\nERROR: free: Attempt to free invalid ID\r\n   At: servers/spatial_sound/spatial_sound_server_sw.cpp:598.\r\nERROR: free: Attempt to free invalid ID\r\n   At: servers/spatial_sound_2d/spatial_sound_2d_server_sw.cpp:612.\r\nWARNING: cleanup: ObjectDB Instances still exist!\r\n   At: core/object.cpp:1904.\r\nERROR: clear: Resources Still in use at Exit!\r\n   At: core/resource.cpp:357.\r\n`\r\n"}],"action":{"name":"View Issue","url":"https://github.com/flossmanualsfr/escoria/issues/1#issuecomment-243177467"}}}

**Comment by nylnook** [comment]
Ok, double checked: I installed Godot from AUR, and it was not updated ...
So: it work with Godot 2.1 stable official, not with the version 2.0 I had. Sorry I wasted your time!

**Comment by punto-** [comment]
```
                                                                                  No problem, it's good to know what is the minimum version we require :)                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Orange network.                                                                                                                                                                                                                From: Camille BissuelSent: Monday, August 29, 2016 5:54 PMTo: flossmanualsfr/escoriaReply To: flossmanualsfr/escoriaCc: punto-; MentionSubject: Re: [flossmanualsfr/escoria] Crash when launching the game on another computer (#1)Ok, double checked: I installed Godot from AUR, and it was not updated ...
```

So: it work with Godot 2.1 stable official, not with the version 2.0 I had. Sorry I wasted your time!

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/flossmanualsfr/escoria","title":"flossmanualsfr/escoria","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/flossmanualsfr/escoria"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nylnook in #1: Ok, double checked: I installed Godot from AUR, and it was not updated ...\r\nSo: it work with Godot 2.1 stable official, not with the version 2.0 I had. Sorry I wasted your time!"}],"action":{"name":"View Issue","url":"https://github.com/flossmanualsfr/escoria/issues/1#issuecomment-243183467"}}}
