### ISSUE TITLE
Credit scene for the game over

### ISSUE THREAD

**Issue by nylnook** [flossmanualsfr/escoria#4]
Right now if we finish the game (win or lose), it result to a crash because there is no credits scene.

I'll try to do one soon.

**Comment by nylnook** [comment]
I added a ui/credits.tscn file, but I suppose there is a credits.gd file missing to make it work in the game... 
I don't know how to do that...
@punto- ?

**Comment by punto-** [comment]
Added a script for the credits scene, it's a menu. Also added a new credits
button in the main menu. The text id for the button is "UI_CREDITS" since
it follows the pattern for all the other buttons.. The actual credits text
I named "CREDITS", it's in the credits scene, so it should be updated in
the translations file.

I made the label in the credits scene a RichTextLabel in case we want to
use bbcode there. We could also put the credits in files like
credits_en.txt, credits_fr.txt, etc, and load them with code if it makes it
easier to edit, just let me know.

Also added the "UI_BACK" text for the button on the credits screen to go
back to the main menu.

**Comment by nylnook** [comment]
Thanks @punto-  !
But it crash for me while playing and finishing the game ... 

```
hud got tooltip text    Utiliser inv_bad_bamboo_2.tooltip avec bamboo_god_2.tooltip
hud got tooltip text    
set state   bamboo_god_2    default angry   False
has animation   True
playing animation   angry
item set speaking!  bamboo_god_2    True    angry
 ** loading speech  res://audio/speech/en/bamboo_god_2_use_2.spx
ERROR: set_file: Condition ' err != OK ' is true.
   At: drivers/speex/audio_stream_speex.cpp:548.
 *** not playing? :(
hud got tooltip text    
item set speaking!  bamboo_god_2    False   angry
set state   bamboo_god_2    angry   angry   True
has animation   True
playing animation   angry
set state   bamboo_god_2    angry   angry   True
has animation   True
playing animation   angry
change scene to     res://game/globals/scene_main.scn
ERROR: get_tree: Condition ' !data.tree ' is true. returned: __null
   At: scene/main/node.h:209.
ERROR: get_tree: Condition ' !data.tree ' is true. returned: __null
   At: scene/main/node.h:209.
ERROR: load_interactive: Condition ' err!=OK ' is true. returned: Ref<ResourceInteractiveLoader>()
   At: core/io/resource_format_binary.cpp:1081.
ERROR: load: Failed loading resource: res://game/globals/scene_main.scn
   At: core/io/resource_loader.cpp:218.
ERROR: get_tree: Condition ' !data.tree ' is true. returned: __null
   At: scene/main/node.h:209.
ERROR: get_tree: Condition ' !data.tree ' is true. returned: __null
   At: scene/main/node.h:209.

```

For the translations, your are right for UI_CREDITS vs CREDITS, and I think everything can be at the same place... no need to create and code credits_en.txt, credits_fr.txt I think, it's quite short in our case. I'll correct the general.csv file ;)

We are almost finish...

**Comment by punto-** [comment]
Fixed :)

**Comment by nylnook** [comment]
Great ! Just tested, it works nicely in every cases ;)
Thanks Ariel !
